/*
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 */

class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var sDic:[Character:Int] = Dictionary()
        for c in s {
            if sDic[c] == nil {
                sDic[c] = 1
            } else {
                sDic[c]! += 1
            }
        }
        for c in t {
            if sDic[c] == nil {
                return c
            } else {
                if sDic[c]! < 1 { return c }
                sDic[c]! -= 1
            }
        }
        return "c"
    }
}

